   services:
     - type: web
       name: ai-text-detector
       env: docker
       region: oregon  # or your preferred region
       plan: free  # or another plan
       branch: main  # or your preferred branch
       healthCheckPath: /
       envVars:
         - key: DATABASE_URL
           fromDatabase:
             name: ai_text_detector_db
             property: connectionString
         - key: SECRET_KEY
           generateValue: true
         - key: WEB_CONCURRENCY
           value: 4

   databases:
     - name: ai_text_detector_db
       databaseName: ai_text_detector
       user: ai_text_detector